In [15]:
import numpy as np
import torch

In [2]:
torch.__version__

'0.4.1'

In [3]:
np.__version__

'1.13.3'

### 1.numpy vs torch
* Torch 自称为神经网络界的 Numpy, 因为他能将 torch 产生的 tensor 放在 GPU 中加速运算 (前提是你有合适的 GPU), 就像 Numpy 会把 array 放在 CPU 中加速运算. 所以神经网络的话, 当然是用 Torch 的 tensor 形式数据最好咯. 就像 Tensorflow 当中的 tensor 一样.
* numpy array 和 torch tensor之间的自由转换

In [7]:
np_data = np.arange(6).reshape((2, 3))
torch_data = torch.from_numpy(np_data)
tensor2_array = torch_data.numpy()
print(
    "np_data:\n",np_data,
    "\ntorch_data:\n", torch_data,
    "\ntensor2_array:\n", tensor2_array,
)

np_data:
 [[0 1 2]
 [3 4 5]] 
torch_data:
 tensor([[0, 1, 2],
        [3, 4, 5]]) 
tensor2_array:
 [[0 1 2]
 [3 4 5]]


### 2.torch中的数学运算
* torch 中 tensor 的运算和 numpy array 的如出一辙,详见中文文档

In [16]:
# abs运算
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data) # 转换成32位浮点 tensor
print(
    "abs",
    "\nnumpy:", np.abs(data),
    "\ntorch:", torch.abs(tensor),
)

# sin
print(
    "sin",
    "\nnumpy:", np.sin(data),
    "\ntorch:", torch.sin(tensor),
)
# mean()
print(
    "mean",
    "\nnumpy:", np.mean(data),
    "\ntorch:", torch.mean(tensor),
)

abs 
numpy: [1 2 1 2] 
torch: tensor([1., 2., 1., 2.])
sin 
numpy: [-0.84147098 -0.90929743  0.84147098  0.90929743] 
torch: tensor([-0.8415, -0.9093,  0.8415,  0.9093])
mean 
numpy: 0.0 
torch: tensor(0.)


* 除了简单的计算, 矩阵运算才是神经网络中最重要的部分. 所以我们展示下矩阵的乘法. 注意以下 ** 包含了一个 numpy 中可行, 但是 torch 中不可行的方式 **.

In [22]:
# matrix multiplication 矩阵点乘
data = [[1, 2], [3, 4]]
tensor = torch.FloatTensor(data)  # 转换成32位浮点 tensor
# 正确方式
print(
    "矩阵点乘matmul",
    "\nnumpy:\n", np.matmul(data, data),
    "\ntorch:\n", torch.mm(tensor, tensor),
)
# !!!!  下面是错误的方法 !!!!
data = np.array(data)
print(
    "矩阵点乘dot",
    "\nnumpy:\n", data.dot(data),  # [[7, 10], [15, 22]] 在numpy 中可行
   # "\ntorch:\n", tensor.dot(tensor),  # # torch 会转换成 [1,2,3,4].dot([1,2,3,4) = 30.0
)

矩阵点乘matmul 
numpy:
 [[ 7 10]
 [15 22]] 
torch:
 tensor([[ 7., 10.],
        [15., 22.]])
矩阵点乘dot 
numpy:
 [[ 7 10]
 [15 22]]
