### 1.什么是Variable
* 在 Torch 中的 Variable 就是一个存放会变化的值的地理位置. 里面的值会不停的变化. 就像一个裝鸡蛋的篮子, 鸡蛋数会不停变动. 那谁是里面的鸡蛋呢, 自然就是 Torch 的 Tensor 咯. 如果用一个 Variable 进行计算, 那返回的也是一个同类型的 Variable.

In [1]:
import torch
from torch.autograd import Variable  # torch 中 Variable 模块

In [2]:
# 先产生鸡蛋
tensor = torch.FloatTensor([[1, 2], [3, 4]])
# 再把鸡蛋放在篮子中，requires_grad是指此变量参不参与误差反向传播, 要不要计算梯度
variable = Variable(tensor, requires_grad=True)  # 默认不计算梯度
print(tensor)
print(variable)

tensor([[1., 2.],
        [3., 4.]])
tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


### 2. Variable计算
* 对比一下 tensor 的计算和 variable 的计算

In [3]:
t_out = torch.mean(tensor*tensor)
v_out = torch.mean(variable*variable)
print("tensor:", t_out)
print("variable:", v_out)

tensor: tensor(7.5000)
variable: tensor(7.5000, grad_fn=<MeanBackward1>)


* 到目前为止, 我们看不出什么不同, ** 但是时刻记住, Variable 计算时, 它在背景屏幕后面都一步步默默地搭建着一个庞大的系统, 叫做计算图, computational graph. 这个图是用来干嘛的? 原来是将所有的计算步骤 (节点) 都连接起来, 最后进行误差反向传递的时候, 一次性将所有 variable 里面的修改幅度 (梯度) 都计算出来, 而 tensor 就没有这个能力啦 **.
* v_out = torch.mean(variable*variable) 就是在计算图中添加的一个计算步骤, 计算误差反向传递的时候有他一份功劳

In [4]:
v_out.backward()  # 模拟 v_out 的误差反向传递

# 下面两步看不懂没关系, 只要知道 Variable 是计算图的一部分, 可以用来传递误差就好.
# v_out = 1/4 * sum(variable*variable) 这是计算图中的 v_out 计算步骤
# 针对于 v_out 的梯度就是, d(v_out)/d(variable) = 1/4*2*variable = variable/2

print(variable.grad)

tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 3.获取 Variable 里面的数据
* 直接 print(variable) 只会输出 Variable 形式的数据, 在很多时候是用不了的(比如想要用 plt 画图), 所以我们要转换一下, 将它变成 tensor 形式.

In [5]:
print(variable)  #  Variable 形式

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
print(variable.data)   # tensor 形式

tensor([[1., 2.],
        [3., 4.]])


In [8]:
print(variable.data.numpy())  # numpy 形式

[[ 1.  2.]
 [ 3.  4.]]
